services:
    contagric.block.resume:
        id: contagric.block.resume
        class:  Contagric\BackendBundle\Block\ResumeBlockService
        arguments:
            - "contagric.block.resume"
            - "@templating"
            - "@doctrine.orm.entity_manager"
        tags:
            - {name: "sonata.block"}
