<?php

namespace Contagric\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FincaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FincaRepository extends EntityRepository
{
}
