<?php

namespace Contagric\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GeneroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeneroRepository extends EntityRepository
{
}
